#include <string>

std::string license = "GDH BETA TEST LICENSE AGREEMENT (20.03.2024)\n"
                      "\n"
                      "THIS SOFTWARE IS PROVIDED FOR BETA TESTING PURPOSES ONLY.\n"
                      "BY USING THIS SOFTWARE, YOU AGREE TO BE BOUND BY THE TERMS\n"
                      "AND CONDITIONS OF THIS AGREEMENT.\n"
                      "\n"
                      "1. Evaluation Period:\n"
                      "   - This beta test version of GDH is provided for a limited\n"
                      "     evaluation period. You may use this software solely for the\n"
                      "     purpose of testing and providing feedback to the developers.\n"
                      "\n"
                      "2. Non-Commercial Use:\n"
                      "   - You are permitted to use this beta test version of GDH for\n"
                      "     non-commercial purposes only. Redistribution or sale of this\n"
                      "     software for commercial gain is strictly prohibited.\n"
                      "\n"
                      "3. Feedback Obligation:\n"
                      "   - As a beta tester, you are encouraged to provide feedback,\n"
                      "     bug reports, and suggestions to the developers to improve\n"
                      "     the quality and functionality of GDH.\n"
                      "\n"
                      "4. Third-party Libraries:\n"
                      "   - This software utilizes the following third-party libraries,\n"
                      "     and you must agree to their respective license agreements:\n"
                      "     - Dear ImGui\n"
                      "     - JSON (nlohmann)\n"
                      "     - MinHook\n"
                      "     - Cocos2d-x\n"
                      "     - Discord RPC\n"
                      "     - GLEW\n"
                      "     - STB Image\n"
                      "\n"
                      "5. No Warranty:\n"
                      "   - This beta test version of GDH is provided \"as is,\" without\n"
                      "     any warranty or guarantee of any kind, express or implied.\n"
                      "     The developers shall not be liable for any damages arising\n"
                      "     from the use or inability to use this software.\n"
                      "\n"
                      "6. Ownership:\n"
                      "   - All rights, title, and interest in and to GDH, including\n"
                      "     any intellectual property rights, are owned by the\n"
                      "     developers. This license does not grant you any ownership\n"
                      "     rights to the software.\n"
                      "\n"
                      "7. Termination:\n"
                      "   - This license is effective until terminated. The developers\n"
                      "     reserve the right to terminate this license at any time\n"
                      "     without prior notice if you fail to comply with any of the\n"
                      "     terms and conditions outlined herein.\n"
                      "\n"
                      "By using this software, you acknowledge that you have read and\n"
                      "understood this Beta Test License Agreement and agree to be bound\n"
                      "by its terms and conditions. If you do not agree with these\n"
                      "terms, you are not authorized to use this software.";
