#include "includes.hpp"

std::string license = "GDH SOURCE CODE LICENSE AGREEMENT (19.01.2024)\n"
"\n"
"NOTICE: THIS SOFTWARE IS PROVIDED \"AS IS\", WITHOUT\n"
"WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING\n"
"BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \n"
"FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.\n"
"YOU ASSUME ALL RESPONSIBILITY FOR THE USE OF THIS SOFTWARE.\n"
"\n"
"1. Copyrights:\n"
"   - The copyrights for this software are owned by TobyAdd.\n"
"\n"
"2. License:\n"
"   - You are granted the right to use, copy, modify, merge,\n"
"   publish, distribute, and/or provide access to the software\n"
"   and its source code, subject to the terms of this license.\n"
"\n"
"3. Sales and Closing Source Code:\n"
"   - It is FORBIDDEN to sell, lease, or transfer ownership of\n"
"   the software or its source code. It is FORBIDDEN to close\n"
"   the source code of the software or provide it only in\n"
"   executable form. The software must remain open and available\n"
"   for free use and modification by the public.\n"
"\n"
"4. Third-Party Libraries:\n"
"   - This software includes third-party libraries such as \n"
"   imgui, json, minhook, cocos2dx. The licenses for these libraries \n"
"   remain unchanged, and you agree to comply with the terms of these \n"
"   licenses when using this software.\n"
"\n"
"5. Disclaimer of Liability:\n"
"   - The author is not liable for any claims, losses, or other\n"
"   liabilities arising out of the use, distribution, or sale\n"
"   of the software.\n"
"\n"
"6. Changes and Modifications:\n"
"   - Any changes and modifications made to the software must\n"
"   be clearly marked and documented, and the modified source\n"
"   code must be provided when distributing.\n"
"\n"
"7. Feedback and Collaboration:\n"
"   - You are encouraged, but not obligated, to provide feedback,\n"
"   bug fixes, and improvements to the public.\n"
"\n"
"8. Termination:\n"
"   - This license is valid until terminated. The author reserves\n"
"   the right to change the terms of the license at their discretion.\n"
"\n"
"SPECIAL THANKS AND RESPECT TO OUR CONTRIBUTORS WHO HAVE\n"
"CONTRIBUTED TO THIS PROJECT.";